#!/usr/bin/env python

from scapy.all import *
import yaml
import time
import logging
import os
import getopt

class CRApvD:
	def __init__(self, config):
		self.config = config
		self.prefixes = {}
		self.timers = {}
		self.prefixesMtime = 0
		self.routerFound = False
		self.keepRunning = True

		logging.basicConfig(filename=self.config['logfile'], level=logging.DEBUG, format='%(asctime)s %(levelname)-8s %(message)s', datefmt='%Y-%m-%d %I:%M:%S')
		logging.info('starting crapvd')

		self.updatePrefixes()

	def run(self):
		logging.info('starting sniffing')
		sniff('icmp6', prn=self.sniffHandler, stop_filter=self.keepSniffing, store=0)
		logging.info('stopped sniffing')

	def keepSniffing(self, x):
		return not self.keepRunning

	def sniffHandler(self, packet):
		# router sollicitation
		if ICMPv6ND_RS in packet:
			logging.info('received RS from %s', packet[IPv6].src)
			# when running in automatic mode, wait for router config being detected
			# prior to responding to router solicitments
			if self.config['automatic'] is True and self.routerFound is False:
				logging.debug('ignoring RS from %s, running in automatic mode and no RA has been received yet' % packet[IPv6].src)
			else:
				# drop timeout for address to below timeout
				self.timers[packet[IPv6].src] = time.time() - (self.config['interval'] + 1)
				logging.debug('dropped timeout to %d for %s' % (self.timers[packet[IPv6].src], packet[IPv6].src))

		# when running in automatic mode, copy data found in first router advertisement
		# and start replying to received router solicitments from now on
		if ICMPv6ND_RA in packet and self.config['automatic'] is True and self.routerFound is False:
			self.routerFound = True
			self.config['srcll'] = packet[IPv6].src
			self.config['srcmac'] = packet[IPv6][ICMPv6ND_RA].lladdr
			logging.info('found RA from %s for %s, from now replying on RS' % (self.config['srcmac'], self.config['srcll']))

		# update prefixes list
		self.updatePrefixes()

		# asynchronously 'schedule' next round of sending directed RA's
		self.checkToSend()

	def checkToSend(self):
		timeout = (time.time() - self.config['interval'])
		for customer in self.prefixes:
			data = self.prefixes[customer]
			if data['lladdr'] not in self.timers:
				self.timers[data['lladdr']] = time.time()
				logging.debug('%s not found in timers, resetting' % data['lladdr'])
			elif self.timers[data['lladdr']] < timeout:
				logging.debug('timeout for %s: %d < %d, sending' % (data['lladdr'], self.timers[data['lladdr']], timeout))
				self.sendRA(data['lladdr'], data['prefix'])

	def sendRA(self, lladdr, prefix):
		logging.info('sending prefix %s to address %s' % (prefix, lladdr))
		# IPv6 packet
		ip6 = IPv6()
		# forge ip6 source address
		ip6.src = self.config['srcll']
		ip6.dst = lladdr
		# make packet an RA
		ra = ICMPv6ND_RA()
		# forge source mac address
		src = ICMPv6NDOptSrcLLAddr()
		src.lladdr = self.config['srcmac']
		# set right prefix data
		preinf = ICMPv6NDOptPrefixInfo()
		preinf.prefix = prefix.split('/')[0]
		preinf.prefixlen = int(prefix.split('/')[1])
		# glue parts together and send it
		if send(ip6/ra/src/preinf) is None:
			logging.debug('sent successful, resetting timer for %s' % lladdr)
			self.timers[lladdr] = time.time()

	def updatePrefixes(self):
		try:
			mtime = os.path.getmtime(self.config['prefixfile'])
			if mtime > self.prefixesMtime:
				if self.prefixesMtime != 0:
					logging.info('prefixes file %s updated, reloading' % self.config['prefixfile'])
				self.prefixesMtime = mtime
				file = open(self.config['prefixfile'], 'r')
				prefixes = yaml.load(file)
				if prefixes:
					self.prefixes = prefixes
					logging.info('%d prefixes loaded from %s' % (len(self.prefixes), self.config['prefixfile']))
				else:
					logging.warning('no prefixes could be found in %s' % self.config['prefixfile'])
		except OSError, e:
			logging.error('prefixes file %s not found' % self.config['prefixfile'])
			self.keepRunning = False

def daemonize (stdin='/dev/null', stdout='/dev/null', stderr='/dev/null'):
	# Do first fork.
	try:
		pid = os.fork()
		if pid > 0:
			sys.exit(0)   # Exit first parent.
	except OSError, e:
		sys.stderr.write("fork #1 failed: (%d) %s\n" % (e.errno, e.strerror))
		sys.exit(1)

	# Decouple from parent environment.
	os.chdir("/")
	os.umask(0)
	os.setsid()

	# Do second fork.
	try:
		pid = os.fork()
		if pid > 0:
			try:
				# write pid file
				f = open('/var/run/crapvd.pid', 'w')
				f.write(str(pid))
				f.close()
			except IOError, e:
				sys.stderr.write("could not write pid to file: (%d) %s\n" % (e.errno, e.strerror))
				sys.exit(1)   # Exit second parent.
			sys.exit(0)   # Exit second parent.
	except OSError, e:
		sys.stderr.write("fork #2 failed: (%d) %s\n" % (e.errno, e.strerror))
		sys.exit(1)

	# daemonizing succeeded
	# Redirect standard file descriptors.
	si = open(stdin, 'r')
	so = open(stdout, 'a+')
	se = open(stderr, 'a+', 0)
	os.dup2(si.fileno(), sys.stdin.fileno())
	os.dup2(so.fileno(), sys.stdout.fileno())
	os.dup2(se.fileno(), sys.stderr.fileno())

def usage():
	print """Usage: %s -s srcll -m srcmac [-i interval] [-c prefixesfile] [-l logfile] [-f] [-a] [-h]

	-s ip6address  : link-local address for real gateway          [required]
	-m macaddress  : mac-address of link-local address            [required]
	-i seconds     : approximate interval advertisements are sent [default=60]
	-c file        : YAML file containing prefixes                [default=/etc/prefixes.yaml]
	-l file        : log file                                     [default=/var/log/crapvd.log]
	-f             : don't detach from foreground
	-a             : crapvd will listen for RA from the real router
	                 both -m and -s will be ignored
	-h             : show this help message
	""" % os.path.basename(sys.argv[0])

if __name__ == '__main__':
	# defaults
	config = {
		'interval': 60,
		'logfile': '/var/log/crapvd.log',
		'prefixfile': '/etc/prefixes.yaml',
		'automatic': False
	}
	foreground = False

	# parse options
	try:
		opts, args = getopt.getopt(sys.argv[1:], 's:m:i:c:l:fah', [])
	except getopt.GetoptError, e:
		print str(e)
		sys.exit(2)

	for o, a in opts:
		if o == '-s':
			config['srcll'] = a
		elif o == '-m':
			config['srcmac'] = a
		elif o == '-i':
			config['interval'] = int(a)
		elif o == '-c':
			config['prefixfile'] = a
		elif o == '-l':
			config['logfile'] = a
		elif o == '-f':
			foreground = True
		elif o == '-h':
			usage()
			sys.exit(0)
		elif o == '-a':
			config['automatic'] = True
		else:
			print "Error: unknown option %s" % o
			usage()
			sys.exit(2)

	# check for required parameters
	if ('srcmac' not in config or 'srcll' not in config) and config['automatic'] is False:
		print "Error: either -a or -s and -m are required"
		usage()
		sys.exit(2)

	# detach from foreground
	if foreground is False:
		daemonize()

	# start daemon
	c = CRApvD(config)
	c.run()
